// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types'
import type { AccountId32 } from 'dedot/codecs'
import type { GenericContractEvents, GenericContractEvent } from 'dedot/contracts'

export interface ContractEvents<ChainApi extends GenericSubstrateApi>
  extends GenericContractEvents<ChainApi> {
  /**
   *
   * @signature_topic: 0x2e8adc6b9a48581f101dedf102a9d58776480169d3eed1db215dff8499622c77
   **/
  ReserveTransferred: GenericContractEvent<
    'ReserveTransferred',
    {
      /**
       *
       * @indexed: true
       **/
      account: AccountId32
      /**
       *
       * @indexed: false
       **/
      amount: bigint
      /**
       *
       * @indexed: false
       **/
      from: number
      /**
       *
       * @indexed: true
       **/
      to: number
    }
  >
}
