// Generated by dedot cli

import type { AccountId32, AccountId32Like, FixedArray, FixedBytes } from 'dedot/codecs'

export type HydraSwapHydrationSwappingCrosschainSwap = {}

export type InkPrimitivesLangError = 'CouldNotReadInput'

export type HydraSwapXcmDepositedLocation =
  | { type: 'Account'; value: AccountId32 }
  | { type: 'Parachain'; value: number }
  | { type: 'ParachainAccount'; value: [number, AccountId32] }

export type HydraSwapXcmDepositedLocationLike =
  | { type: 'Account'; value: AccountId32Like }
  | { type: 'Parachain'; value: number }
  | { type: 'ParachainAccount'; value: [number, AccountId32Like] }

export type PopApiStatusCode = number

export type StagingXcmV4Asset = { id: StagingXcmV4AssetAssetId; fun: StagingXcmV4AssetFungibility }

export type StagingXcmV4AssetLike = {
  id: StagingXcmV4AssetAssetIdLike
  fun: StagingXcmV4AssetFungibilityLike
}

export type StagingXcmV4AssetAssetId = StagingXcmV4Location

export type StagingXcmV4AssetAssetIdLike = StagingXcmV4LocationLike

export type StagingXcmV4Location = { parents: number; interior: StagingXcmV4Junctions }

export type StagingXcmV4LocationLike = { parents: number; interior: StagingXcmV4JunctionsLike }

export type StagingXcmV4Junctions =
  | { type: 'Here' }
  | { type: 'X1'; value: FixedArray<StagingXcmV4Junction, 1> }
  | { type: 'X2'; value: FixedArray<StagingXcmV4Junction, 2> }
  | { type: 'X3'; value: FixedArray<StagingXcmV4Junction, 3> }
  | { type: 'X4'; value: FixedArray<StagingXcmV4Junction, 4> }
  | { type: 'X5'; value: FixedArray<StagingXcmV4Junction, 5> }
  | { type: 'X6'; value: FixedArray<StagingXcmV4Junction, 6> }
  | { type: 'X7'; value: FixedArray<StagingXcmV4Junction, 7> }
  | { type: 'X8'; value: FixedArray<StagingXcmV4Junction, 8> }

export type StagingXcmV4JunctionsLike =
  | { type: 'Here' }
  | { type: 'X1'; value: FixedArray<StagingXcmV4JunctionLike, 1> }
  | { type: 'X2'; value: FixedArray<StagingXcmV4JunctionLike, 2> }
  | { type: 'X3'; value: FixedArray<StagingXcmV4JunctionLike, 3> }
  | { type: 'X4'; value: FixedArray<StagingXcmV4JunctionLike, 4> }
  | { type: 'X5'; value: FixedArray<StagingXcmV4JunctionLike, 5> }
  | { type: 'X6'; value: FixedArray<StagingXcmV4JunctionLike, 6> }
  | { type: 'X7'; value: FixedArray<StagingXcmV4JunctionLike, 7> }
  | { type: 'X8'; value: FixedArray<StagingXcmV4JunctionLike, 8> }

export type StagingXcmV4Junction =
  | { type: 'Parachain'; value: number }
  | { type: 'AccountId32'; value: [StagingXcmV4JunctionNetworkId | undefined, FixedBytes<32>] }
  | { type: 'AccountIndex64'; value: [StagingXcmV4JunctionNetworkId | undefined, bigint] }
  | { type: 'AccountKey20'; value: [StagingXcmV4JunctionNetworkId | undefined, FixedBytes<20>] }
  | { type: 'PalletInstance'; value: number }
  | { type: 'GeneralIndex'; value: bigint }
  | { type: 'GeneralKey'; value: [number, FixedBytes<32>] }
  | { type: 'OnlyChild' }
  | { type: 'Plurality'; value: [XcmV3JunctionBodyId, XcmV3JunctionBodyPart] }
  | { type: 'GlobalConsensus'; value: StagingXcmV4JunctionNetworkId }

export type StagingXcmV4JunctionLike =
  | { type: 'Parachain'; value: number }
  | { type: 'AccountId32'; value: [StagingXcmV4JunctionNetworkIdLike | undefined, FixedBytes<32>] }
  | { type: 'AccountIndex64'; value: [StagingXcmV4JunctionNetworkIdLike | undefined, bigint] }
  | { type: 'AccountKey20'; value: [StagingXcmV4JunctionNetworkIdLike | undefined, FixedBytes<20>] }
  | { type: 'PalletInstance'; value: number }
  | { type: 'GeneralIndex'; value: bigint }
  | { type: 'GeneralKey'; value: [number, FixedBytes<32>] }
  | { type: 'OnlyChild' }
  | { type: 'Plurality'; value: [XcmV3JunctionBodyIdLike, XcmV3JunctionBodyPart] }
  | { type: 'GlobalConsensus'; value: StagingXcmV4JunctionNetworkIdLike }

export type StagingXcmV4JunctionNetworkId =
  | { type: 'ByGenesis'; value: FixedBytes<32> }
  | { type: 'ByFork'; value: [bigint, FixedBytes<32>] }
  | { type: 'Polkadot' }
  | { type: 'Kusama' }
  | { type: 'Westend' }
  | { type: 'Rococo' }
  | { type: 'Wococo' }
  | { type: 'Ethereum'; value: bigint }
  | { type: 'BitcoinCore' }
  | { type: 'BitcoinCash' }
  | { type: 'PolkadotBulletin' }

export type StagingXcmV4JunctionNetworkIdLike =
  | { type: 'ByGenesis'; value: FixedBytes<32> }
  | { type: 'ByFork'; value: [bigint, FixedBytes<32>] }
  | { type: 'Polkadot' }
  | { type: 'Kusama' }
  | { type: 'Westend' }
  | { type: 'Rococo' }
  | { type: 'Wococo' }
  | { type: 'Ethereum'; value: bigint }
  | { type: 'BitcoinCore' }
  | { type: 'BitcoinCash' }
  | { type: 'PolkadotBulletin' }

export type XcmV3JunctionBodyId =
  | { type: 'Unit' }
  | { type: 'Moniker'; value: FixedBytes<4> }
  | { type: 'Index'; value: number }
  | { type: 'Executive' }
  | { type: 'Technical' }
  | { type: 'Legislative' }
  | { type: 'Judicial' }
  | { type: 'Defense' }
  | { type: 'Administration' }
  | { type: 'Treasury' }

export type XcmV3JunctionBodyIdLike =
  | { type: 'Unit' }
  | { type: 'Moniker'; value: FixedBytes<4> }
  | { type: 'Index'; value: number }
  | { type: 'Executive' }
  | { type: 'Technical' }
  | { type: 'Legislative' }
  | { type: 'Judicial' }
  | { type: 'Defense' }
  | { type: 'Administration' }
  | { type: 'Treasury' }

export type XcmV3JunctionBodyPart =
  | { type: 'Voice' }
  | { type: 'Members'; value: number }
  | { type: 'Fraction'; value: [number, number] }
  | { type: 'AtLeastProportion'; value: [number, number] }
  | { type: 'MoreThanProportion'; value: [number, number] }

export type StagingXcmV4AssetFungibility =
  | { type: 'Fungible'; value: bigint }
  | { type: 'NonFungible'; value: StagingXcmV4AssetAssetInstance }

export type StagingXcmV4AssetFungibilityLike =
  | { type: 'Fungible'; value: bigint }
  | { type: 'NonFungible'; value: StagingXcmV4AssetAssetInstanceLike }

export type StagingXcmV4AssetAssetInstance =
  | { type: 'Undefined' }
  | { type: 'Index'; value: bigint }
  | { type: 'Array4'; value: FixedBytes<4> }
  | { type: 'Array8'; value: FixedBytes<8> }
  | { type: 'Array16'; value: FixedBytes<16> }
  | { type: 'Array32'; value: FixedBytes<32> }

export type StagingXcmV4AssetAssetInstanceLike =
  | { type: 'Undefined' }
  | { type: 'Index'; value: bigint }
  | { type: 'Array4'; value: FixedBytes<4> }
  | { type: 'Array8'; value: FixedBytes<8> }
  | { type: 'Array16'; value: FixedBytes<16> }
  | { type: 'Array32'; value: FixedBytes<32> }

export type InkEnvNoChainExtension = null
